//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VDFilters.rc
//
#define IDC_PREVIEW                     3
#define IDC_SAMPLE                      4
#define IDD_FILTER_SINGVAR              115
#define IDD_FILTER_BRIGHTCONT           116
#define IDD_FILTER_SMOOTHER             202
#define IDD_FILTER_DEINTERLACE          203
#define IDD_FILTER_ROTATE2              207
#define IDD_FILTER_BOX                  233
#define IDD_FILTER_TIMESMOOTH           237
#define IDD_FILTER_HSV                  243
#define IDD_FILTER_CHROMASMOOTHER       260
#define IDD_FILTER_PERSPECTIVE          264
#define IDD_FILTER_WARPRESIZE           271
#define IDD_FILTER_CONVERTFORMAT        274
#define IDD_FILTER_BOBDOUBLER           277
#define IDD_FILTER_WARPSHARP            278
#define IDD_FILTER_INTERPOLATE          281
#define IDD_FILTER_INTERLACE            282
#define IDD_FILTER_IVTC                 283
#define IDD_FILTER_GAMMACORRECT         290
#define IDC_BLEND_MODE                  1001
#define IDC_MODE_Y                      1002
#define IDC_AMOUNT                      1002
#define IDC_MODE_I                      1003
#define IDC_STATIC_AMOUNT               1003
#define IDC_MODE_Q                      1004
#define IDC_MODE_IQAVERAGE3             1005
#define IDC_MODE_IQAVERAGE5             1006
#define IDC_MODE_IQAV5TMP               1007
#define IDC_MODE_CHROMAUP               1008
#define IDC_MODE_CHROMADOWN             1009
#define IDC_FRAMERATE_TARGET            1023
#define IDC_SLIDER                      1066
#define IDC_BRIGHTNESS                  1068
#define IDC_CONTRAST                    1069
#define IDC_HEIGHT                      1074
#define IDC_WIDTH                       1136
#define IDC_EDIT_SCALE                  1152
#define IDC_ANGLE                       1152
#define IDC_PHASE                       1152
#define IDC_EDIT_TARGET                 1153
#define IDC_EXPANDBOUNDS                1184
#define IDC_UNPROJECT                   1184
#define IDC_SHOW_GRADIENT               1184
#define IDC_PREFILTER                   1184
#define IDC_COLOR                       1196
#define IDC_VALUE                       1240
#define IDC_PICKCOLOR                   1282
#define IDC_MODE_INTERP_YADIF           1291
#define IDC_ROTATE_LEFT                 1292
#define IDC_MODE_INTERP_BOB             1292
#define IDC_ROTATE_RIGHT                1293
#define IDC_MODE_DUP                    1293
#define IDC_ROTATE_180                  1294
#define IDC_FILTERMODE                  1294
#define IDC_MODE_DISCARD                1294
#define IDC_MODE_INTERP_ELA             1295
#define IDC_MODE_UNFOLD                 1296
#define IDC_MODE_FOLD                   1297
#define IDC_MODE_INTERP_BLEND           1298
#define IDC_FORMATS                     1317
#define IDC_SLIDER_WIDTH                1351
#define IDC_SLIDER_POWER                1352
#define IDC_STATIC_WIDTH                1353
#define IDC_STATIC_POWER                1354
#define IDC_STRENGTH                    1371
#define IDC_EVEN_NONE                   1379
#define IDC_EVEN_SMOOTH                 1380
#define IDC_EVEN_HALFUP                 1381
#define IDC_EVEN_HALFDOWN               1382
#define IDC_ODD_NONE                    1383
#define IDC_ODD_SMOOTH                  1384
#define IDC_ODD_HALFUP                  1385
#define IDC_ODD_HALFDOWN                1386
#define IDC_HUE                         1386
#define IDC_SATURATION                  1387
#define IDC_STATIC_HUE                  1388
#define IDC_STATIC_SATURATION           1389
#define IDC_STATIC_VALUE                1390
#define IDC_MODE_420MPEG1               1405
#define IDC_MODE_420MPEG2               1406
#define IDC_FILTER                      1407
#define IDC_MODE_410                    1407
#define IDC_FIELD                       1408
#define IDC_MODE_411                    1408
#define IDC_MODE_422                    1409
#define IDC_MODE_DISABLE                1410
#define IDC_DEPTH                       1428
#define IDC_SETTING                     1430
#define IDC_FIELDORDER_TFF              1444
#define IDC_FIELDORDER_BFF              1445
#define IDC_PHASE_ADAPTIVE              1446
#define IDC_DEINTERLACE_BOB             1446
#define IDC_PHASE_MANUAL                1447
#define IDC_DEINTERLACE_ELA             1447
#define IDC_FIELDORDER_BLURRED          1448
#define IDC_DEINTERLACE_ADAPTIVEELA     1448
#define IDC_BLUR                        1448
#define IDC_FIELDORDER_DUPLICATED       1449
#define IDC_DEINTERLACE_NONEHALF        1449
#define IDC_STATIC_DEPTH                1449
#define IDC_DEINTERLACE_NONEFULL        1450
#define IDC_STATIC_BLUR                 1450
#define IDC_FRAMERATE_SCALE             1454
#define IDC_INTERP_NONE                 1456
#define IDC_INTERP_LINEAR               1457
#define IDC_FIELDORDER_EVENFIRST        1460
#define IDC_FIELDORDER_ODDFIRST         1461
#define IDC_SOURCE_PROGRESSIVE          1462
#define IDC_SOURCE_ALTERNATING          1463
#define IDC_MODE_DECOMB                 1463
#define IDC_MODE_REDUCE                 1464
#define IDC_FIELDORDER_AUTO             1465
#define IDC_FIELDMODE_KEEPTOP           1466
#define IDC_FIELDMODE_KEEPBOTTOM        1467
#define IDC_FIELDMODE_DOUBLETFF         1468
#define IDC_FIELDMODE_DOUBLEBFF         1469
#define IDC_FIELDMODE_TFFTOBFF          1480
#define IDC_FIELDMODE_BFFTOTFF          1481
#define IDC_LINEARTOSRGB                1482
#define IDC_SRGBTOLINEAR                1483
#define IDC_CS_NONE                     1492
#define IDC_CS_601                      1493
#define IDC_CS_709                      1494
#define IDC_CR_NONE                     1495
#define IDC_CR_LIMITED                  1496
#define IDC_CR_FULL                     1497
#define IDC_STATIC_COLORSPACE           1498
#define IDC_BLEND_WEIGHTING             1522
#define IDD_FILTER_ALIASFORMAT          2001
#define IDD_FILTER_TV                   2002
#define IDD_FILTER_ROTATE               2003
#define IDD_FILTER_FIELDBOB             2004
#define IDD_FILTER_FIELDDELAY           2005
#define IDD_FILTER_BLENDLAYERS          2006
#define IDD_FILTER_MERGELAYERS          2007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2007
#define _APS_NEXT_COMMAND_VALUE         55001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           2001
#endif
#endif
