//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VirtualDub.rc
//
#define IDC_HELP2                       0
#define IDS_TITLE_INITIAL               1
#define IDS_TITLE_NOFILE                2
#define IDC_ADD                         3
#define IDC_LOAD                        3
#define IDS_TITLE_IDLE                  3
#define IDC_SAVE                        3
#define IDC_MOVE_UP                     3
#define IDC_ACCEPT                      3
#define IDC_PREVIEW                     3
#define IDC_SAVEASDEFAULT               3
#define IDOK2                           3
#define IDC_ADDTOQUEUE                  3
#define IDC_DELETE_ALL                  3
#define IDC_REMOVE                      4
#define IDS_TITLE_DUBBING               4
#define IDC_MOVE_DOWN                   4
#define IDC_SAMPLE                      4
#define IDC_DEL                         4
#define IDC_ARRANGE                     4
#define IDC_ALTOK                       4
#define IDC_SAVE_AS_DEFAULT             4
#define IDC_HELP3                       4
#define IDC_DEBUG                       4
#define IDC_RENAMEFILES                 4
#define IDCANCEL2                       4
#define IDCANCEL4                       4
#define IDC_ONOFF                       4
#define IDC_MOVEUP                      5
#define IDS_TITLE_DUBBING_MINIMIZED     5
#define IDC_SAMPLE_MULTIPLE             5
#define IDC_CLEAR                       5
#define IDC_APPLY                       5
#define IDC_FILTEROUTPUTNAMES           5
#define IDC_RESET                       5
#define IDC_DUPLICATE                   5
#define IDC_MOVEDOWN                    6
#define IDS_TITLE_STATUS                6
#define IDC_POSTPONE                    6
#define IDC_CONFIGURE                   7
#define IDS_TITLE_SERVING               7
#define IDC_POSTPONE2                   7
#define IDC_CLIPPING                    8
#define IDS_TITLE_CAPTURE               8
#define IDC_ABOUT                       8
#define IDS_TITLE_FRAMESERVER           9
#define IDC_BLENDING                    9
#define IDC_PIXELFORMAT                 9
#define IDS_TITLE_CAPTURE2              10
#define IDC_OPTIONS                     10
#define IDC_DELETE                      11
#define IDS_TITLE_IDLE2                 11
#define IDS_TITLE_CAPTURE3              12
#define IDC_TEST                        12
#define IDC_START                       13
#define IDC_START2                      14
#define IDC_RELOAD                      14
#define IDC_SAVE2                       16
#define IDC_SAVEPLUS                    17
#define IDD_MAIN_WINDOW                 101
#define IDR_MAIN_MENU                   102
#define IDD_YIQ_CONFIG                  102
#define IDD_DUBBING                     103
#define IDD_INTERLEAVE                  104
#define IDD_OUTPUT_FORMAT               105
#define IDD_VIDEO_DEPTH                 105
#define IDD_PERFORMANCE                 106
#define IDD_VIDEO_FRAMERATE             107
#define IDR_RESOURCES                   107
#define IDD_FILTERS                     108
#define IDD_FILTER_LIST                 109
#define IDD_ABOUT                       110
#define IDD_FILTER_CONVOLUTE            111
#define IDD_AUDIO_CONVERSION            112
#define IDD_APNG_INFO                   113
#define IDD_AVI_INFO                    114
#define IDD_FILTER_EMBOSS               117
#define IDD_GIF_INFO                    118
#define IDD_IMAGES_INFO                 119
#define IDD_FILTER_CLIPPING             120
#define IDD_VIDEO_CLIPPING              121
#define IDD_CHANGELOG                   124
#define IDD_SHOWTEXT                    124
#define IDR_CHANGES                     127
#define IDD_FILTER_HRESYNC              128
#define IDS_LOG_BANNER1                 128
#define IDR_DUB_MENU                    129
#define IDR_IDLE_KEYS                   131
#define IDI_VIRTUALDUB                  132
#define IDR_CAPTURE_MENU                133
#define IDR_CAPTURE_AUXMENU             134
#define IDD_CAPTURE_PREALLOCATE         135
#define IDD_CAPTURE_SETTINGS            136
#define IDD_CAPTURE_AUDIO_VUMETER       137
#define IDD_DISASM                      138
#define IDR_RELEASE_NOTES               139
#define IDD_PERF_DYNAMIC                140
#define IDD_FILTER_RESIZE               141
#define IDD_FILTER_FILL                 142
#define IDI_POS_BACKWARD                147
#define IDI_POS_FORWARD                 148
#define IDI_POS_START                   149
#define IDI_POS_END                     150
#define IDI_POS_MARKIN                  151
#define IDI_POS_MARKOUT                 152
#define IDI_POS_STOP                    153
#define IDI_POS_PLAY                    154
#define IDI_POS_PREV_KEY                155
#define IDI_POS_NEXT_KEY                156
#define IDD_IMPORT_MPEG                 157
#define IDD_PROGRESS                    157
#define IDI_POS_PLAYPREVIEW             157
#define IDD_IMPORTOPT_AVI               160
#define IDD_IMPORTOPT_MPEG              161
#define IDD_IMPORT_OPTIONS              162
#define IDD_SERVER                      163
#define IDD_SERVER_SETUP                164
#define IDD_CAPTURE_HISTOGRAM           165
#define IDR_CAPTURE_KEYS                166
#define IDD_CAPTURE_PREFERENCES         167
#define IDR_SCRIPTED_MENU               173
#define IDR_SCRIPTED_AUXMENU            175
#define IDD_AVIOUTPUTIMAGES_FORMAT      176
#define IDD_CAPTURE_HITOK               177
#define IDI_POS_SCENEFWD                178
#define IDI_POS_SCENEREV                179
#define IDD_OPEN_AVI                    180
#define IDD_OPEN_AVI1                   180
#define IDD_EXTOPENOPTS_MPEG            181
#define IDD_EXTOPENOPTS_AVI             182
#define IDD_JOBCONTROL                  185
#define IDD_SAVE_OUTPUT                 186
#define IDD_JOBERROR                    187
#define IDR_JOBS_MENU                   188
#define IDD_MPEG_INFO                   189
#define IDD_CAPTURE_PANEL               190
#define IDD_DUBBING_MAIN                191
#define IDD_DUBBING_VIDEO               192
#define IDD_COACH                       193
#define IDD_CAPTURE_STOPCOND            195
#define IDD_CAPTURE_DISKIO              196
#define IDD_CAPTURE_SPILLSETUP          197
#define IDD_VIDEOCOMPRESSION            198
#define IDD_DISASM_CRASH                199
#define IDD_DUBBING_PERF                200
#define IDD_WELCOME                     201
#define IDR_DISPLAY_MENU                206
#define IDD_RESYNCLAB                   208
#define IDD_DEBUGVAL                    209
#define IDD_WARN_MPEG4                  210
#define IDD_EXTOPENOPTS_ASF             211
#define IDD_FILTER_PREVIEW              212
#define IDD_FILTER_GAMMA                213
#define IDD_FILTER_LEVELS               214
#define IDD_FILTER_SAMPLE               215
#define IDD_CAPTURE_CUSTOMVIDEO         216
#define IDD_SAVE_SEGMENTED              217
#define IDD_FILTER_ECHOCANCEL           218
#define IDD_CAPTURE_TIMING              219
#define IDD_CAPTURE_NOISEREDUCTION      220
#define IDR_CAPTURE_ACTIVEMENU          221
#define IDD_CAPTURE_EVENTLOG            222
#define IDD_AUDIOCOMPRESSION            223
#define IDD_CAPTURE_CLIPPING            224
#define IDR_CREDITS                     226
#define IDR_HEXVIEWER_MENU              228
#define IDD_HEXVIEWER                   229
#define IDD_JUMPTOFRAME                 230
#define IDD_OPEN_AVI2                   231
#define IDD_APPEND_AVI                  231
#define IDR_LICENSE                     231
#define IDD_LICENSE                     232
#define IDD_DIVX_WARNING                234
#define IDD_CAPTURE_BT8X8               235
#define IDD_HEXVIEWER_FIND              236
#define IDD_AUDIO_VOLUME                238
#define IDD_HEXVIEWER_RIFFLIST          239
#define IDD_FILTER_LOGO                 241
#define IDD_JOBFINISH                   244
#define IDD_CRASH                       245
#define IDD_AF_SETUP                    246
#define IDD_AF_XPASS                    247
#define IDD_AF_RESAMPLE                 248
#define IDD_AF_PITCHSHIFT               249
#define IDD_AF_STRETCH                  250
#define IDD_AF_LIST                     251
#define IDD_AF_GAIN                     252
#define IDD_LOG                         253
#define IDD_ERRORMODE                   254
#define IDD_WITHERRORS                  255
#define IDD_JOBLOG                      256
#define IDD_DUBBING_LOG                 257
#define IDR_DUB_KEYS                    257
#define IDD_PROFILER                    258
#define IDR_PREVIEW_KEYS                258
#define IDD_AF_NEWRATE                  259
#define IDR_LOG_MENU                    261
#define IDD_EXPERIMENTAL                262
#define IDD_CHANGE_LOG                  265
#define IDD_CAPTURE_BROKEN              266
#define IDD_FILE_SETTEXTINFO            267
#define IDD_AF_FORMATCONV               268
#define IDC_DRAGPOINT                   269
#define IDC_ADDPOINT                    270
#define IDR_AUDIODISPLAY_MENU           270
#define IDC_REMOVEPOINT                 271
#define IDC_ADDPOINT1                   272
#define IDC_MODIFYPOINT                 272
#define IDD_AF_TIMESTRETCH              272
#define IDD_EXTOPENOPTS_MP3             275
#define IDD_FILTER_PREVIEW_ZOOM         276
#define IDD_BATCH_WIZARD                279
#define IDD_BATCH_WIZARD_NAMEFILTER     280
#define IDR_BATCHWIZARD_MENU            281
#define IDD_CONFIGURE_ACCELS            284
#define IDR_FRAME_SYSTEM_MENU           285
#define IDD_FILTER_TEST                 286
#define IDD_DIALOG1                     288
#define IDD_FILTER_OPTIONS              288
#define IDD_DUMPSTATUS                  289
#define IDD_OUTPUT_RAWVIDEO             291
#define IDD_EXTOPENOPTS_RAWVIDEO        292
#define IDD_SELECT_VIDEO_FORMAT         293
#define IDD_OUTPUT_CLI                  295
#define IDD_EXTENC_EDIT_MAIN            296
#define IDD_EXTENC_EDIT_AUDIO           297
#define IDD_EXTENC_EDIT                 298
#define IDD_EXTENC_SETS                 299
#define IDD_EXTENC_EDIT_SET             300
#define IDD_AUTORECOVER                 301
#define IDR_FILTER_LIST_CONTEXT         303
#define IDD_FILTER_OUTPUT_NAME          304
#define IDD_PLUGINS                     305
#define IDD_EXTENC_EDIT_VIDEO           306
#define IDD_SAVEIMAGE_FORMAT            307
#define IDR_FILE_EXPORTMENU             308
#define IDD_FILTER_BLENDING             308
#define IDR_TOOLS_MENU                  309
#define IDD_SAVEVIDEO_FORMAT            309
#define IDD_OPENVIDEO                   310
#define IDD_CAPTURE_AUDIO_MASK          312
#define IDC_CURRENT_VFRAME              1000
#define IDC_CURRENT_ASAMPLE             1001
#define IDC_TIME_REMAINING              1002
#define IDC_TIME_ELAPSED                1003
#define IDC_CURRENT_VSIZE               1004
#define IDC_CURRENT_ASIZE               1005
#define IDC_INTERLEAVE                  1006
#define IDC_PROJECTED_FSIZE             1006
#define IDC_FPS                         1007
#define IDC_PRELOAD                     1008
#define IDC_INTERVAL                    1009
#define IDC_FRAMES                      1010
#define IDC_MS                          1011
#define IDC_OUTPUT_16BIT                1012
#define IDC_DISPLACEMENT                1012
#define IDC_OUTPUT_24BIT                1013
#define IDC_OUTPUT_32BIT                1014
#define IDC_OUTPUT_BUFFER               1015
#define IDC_INPUT_16BIT                 1015
#define IDC_INPUT_XRGB1555              1015
#define IDC_BUFFER_SIZE                 1016
#define IDC_OUTPUT_BUFFER_SIZE          1016
#define IDC_INPUT_24BIT                 1016
#define IDC_INPUT_RGB888                1016
#define IDC_DECIMATE_1                  1017
#define IDC_WAVE_INPUT_BUFFER           1017
#define IDC_INPUT_RGB565                1017
#define IDC_DECIMATE_2                  1018
#define IDC_BUFFER_SIZE2                1018
#define IDC_WAVE_BUFFER_SIZE            1018
#define IDC_INPUT_XRGB8888              1018
#define IDC_DECIMATE_3                  1019
#define IDC_PIPE_BUFFERS                1019
#define IDC_INPUT_YUV422_UYVY           1019
#define IDC_DECIMATE_N                  1020
#define IDC_STATIC_PIPE_BUFFERS         1020
#define IDC_INPUT_YUV422_YUY2           1020
#define IDC_STATIC_VIDEO_BUFFERS        1020
#define IDC_DECIMATE_VALUE              1021
#define IDC_INPUT_YUV420_PLANAR         1021
#define IDC_AUDIO_BUFFER                1021
#define IDC_DECIMATE_TARGET             1022
#define IDC_OUTPUT_XRGB1555             1022
#define IDC_STATIC_AUDIO_BUFFER         1022
#define IDC_INPUT_YUV420_PLANAR16       1022
#define IDC_FILTER_LIST                 1023
#define IDC_FRAMERATE_TARGET            1023
#define IDC_OUTPUT_RGB565               1023
#define IDC_FILTER_INFO                 1024
#define IDS_FILE_OPENAVI                1024
#define IDC_OUTPUT_RGB888               1024
#define IDC_PROGRESS                    1025
#define IDS_FILE_PREVIEWAVI             1025
#define IDC_OUTPUT_XRGB8888             1025
#define IDS_FILE_SAVEAVI                1026
#define IDC_OUTPUT_YUV422_UYVY          1026
#define IDC_DRAW_INPUT                  1027
#define IDS_FILE_CLOSEAVI               1027
#define IDC_OUTPUT_YUV422_YUY2          1027
#define IDC_DRAW_OUTPUT                 1028
#define IDC_MATRIX_1                    1028
#define IDS_FILE_CAPTUREAVI             1028
#define IDC_OUTPUT_YUV420_PLANAR        1028
#define IDC_MATRIX_2                    1029
#define IDS_FILE_AVIINFO                1029
#define IDC_INPUT_YUV422_PLANAR         1029
#define IDC_DRAW_DOUTPUT                1029
#define IDC_MATRIX_3                    1030
#define IDS_FILE_SAVEWAV                1030
#define IDC_INPUT_YUV410_PLANAR         1030
#define IDC_MATRIX_4                    1031
#define IDS_FILE_QUIT                   1031
#define IDC_OUTPUT_YUV422_PLANAR        1031
#define IDC_INPUT_YUV422_PLANAR16       1031
#define IDC_MATRIX_5                    1032
#define IDS_FILE_STARTSERVER            1032
#define IDC_OUTPUT_YUV410_PLANAR        1032
#define IDC_MATRIX_6                    1033
#define IDS_FILE_SAVESTRIPEDAVI         1033
#define IDC_INPUT_Y8                    1033
#define IDC_MATRIX_7                    1034
#define IDS_FILE_SAVEIMAGESEQ           1034
#define IDC_OUTPUT_Y8                   1034
#define IDC_MATRIX_8                    1035
#define IDS_FILE_SAVECOMPATIBLEAVI      1035
#define IDC_INPUT_AUTOSELECT            1035
#define IDC_MATRIX_9                    1036
#define IDS_FILE_LOADCONFIGURATION      1036
#define IDC_OUTPUT_AUTOSELECT           1036
#define IDC_ENABLE_CLIPPING             1037
#define IDS_FILE_SAVECONFIGURATION      1037
#define IDC_INPUT_YUV444_PLANAR         1037
#define IDC_BIAS                        1038
#define IDS_FILE_PREVIEWINPUT           1038
#define IDC_OUTPUT_YUV444_PLANAR        1038
#define IDC_INPUT_YUV444_PLANAR16       1038
#define IDC_SAMPLINGRATE_11KHZ          1039
#define IDS_FILE_PREVIEWOUTPUT          1039
#define IDC_INPUT_YUV422_V210           1039
#define IDC_SAMPLINGRATE_NOCHANGE       1040
#define IDS_FILE_APPENDSEGMENT          1040
#define IDC_OUTPUT_YUV422_V210          1040
#define IDC_SAMPLINGRATE_16KHZ          1041
#define IDS_FILE_SAVESEGMENTEDAVI       1041
#define IDC_INPUT_YUV422_UYVY_709       1041
#define IDC_SAMPLINGRATE_48KHZ          1042
#define IDC_OUTPUT_YUV422_UYVY_709      1042
#define IDC_SAMPLINGRATE_8KHZ           1043
#define IDC_INPUT_YUV420_NV12           1043
#define IDC_SAMPLINGRATE_CUSTOM         1044
#define IDC_OUTPUT_YUV420_NV12          1044
#define IDC_INPUT_I8                    1045
#define IDC_OUTPUT_I8                   1046
#define IDC_SAMPLINGRATE_22KHZ          1047
#define IDC_INPUT_OTHER                 1047
#define IDC_SAMPLINGRATE_44KHZ          1048
#define IDC_OUTPUT_OTHER                1048
#define IDC_SAMPLINGRATE_INTEGRAL       1049
#define IDC_INPUT_XRGB64                1049
#define IDC_BANDWIDTH_REQD              1050
#define IDC_OUTPUT_XRGB64               1050
#define IDC_FRAMERATE_NOCHANGE          1051
#define IDC_SAMPLINGRATE_HQ             1051
#define IDC_FRAMERATE_CHANGE            1052
#define IDC_FRAMERATE                   1053
#define IDC_VIDEO_FPS                   1054
#define IDC_VIDEO_NUMFRAMES             1055
#define IDC_AUDIO_SAMPLINGRATE          1056
#define IDC_AUDIO_CHANNELS              1057
#define IDC_AUDIO_PRECISION             1058
#define IDC_AUDIO_NUMFRAMES             1059
#define IDC_VIDEO_COMPRESSION           1060
#define IDC_VIDEO_NUMKEYFRAMES          1061
#define IDC_VIDEO_KEYFRAMESIZES         1062
#define IDC_VIDEO_NONKEYFRAMESIZES      1063
#define IDC_AUDIO_FRAMESIZES            1064
#define IDC_AUDIO_PRELOAD               1065
#define IDC_AUDIO_LAYOUT                1065
#define IDC_AUDIO_COMPRESSION           1066
#define IDC_HEIGHT                      1074
#define IDC_FRAMEHEIGHT                 1075
#define IDC_HROT                        1075
#define IDC_VROT                        1076
#define IDC_RELHEIGHT                   1076
#define IDC_ROLL                        1077
#define IDC_NEARPT                      1078
#define IDC_ROUNDED                     1079
#define IDC_ZOOM                        1079
#define IDC_PRIORITY                    1080
#define IDC_OFFSET_X1_SPIN              1081
#define IDC_OFFSET_X1                   1082
#define IDC_OFFSET_Y1                   1083
#define IDC_OFFSET_Y1_SPIN              1084
#define IDC_OFFSET_X2                   1085
#define IDC_OFFSET_X2_SPIN              1086
#define IDC_OFFSET_Y2                   1087
#define IDC_OFFSET_Y2_SPIN              1088
#define IDC_STATIC_OFFSET_X2            1089
#define IDC_STATIC_OFFSET_Y2            1090
#define IDC_START_MS                    1091
#define IDC_START_FRAMES                1092
#define IDC_LENGTH_MS                   1093
#define IDC_LENGTH_FRAMES               1094
#define IDC_END_MS                      1095
#define IDC_END_FRAMES                  1096
#define IDC_OFFSET_AUDIO                1097
#define IDC_CLIP_AUDIO                  1098
#define IDC_CHANGES                     1098
#define IDC_BLACK_LEVEL                 1099
#define IDC_CLIP_AUDIO2                 1099
#define IDC_EDIT_AUDIO                  1099
#define IDC_BORDERS                     1105
#define IDC_ABORT                       1107
#define IDC_DISK_SPACE_ALLOCATE         1108
#define IDC_DISK_FREE_SPACE             1109
#define IDC_STATIC_DISK_FREE_SPACE      1110
#define IDC_CAPTURE_AUDIO               1112
#define IDC_CAPTURE_ABORT_ON_LEFT       1113
#define IDC_CAPTURE_ABORT_ON_RIGHT      1114
#define IDC_CAPTURE_LOCK_TO_AUDIO       1116
#define IDC_CAPTURE_ON_OK               1117
#define IDC_CAPTURE_MAX_INDEX           1118
#define IDC_CAPTURE_CPU_POWER           1118
#define IDC_CAPTURE_DROP_LIMIT          1119
#define IDC_CAPTURE_VIDEO_BUFFERS       1120
#define IDC_CAPTURE_AUDIO_BUFFERS       1121
#define IDC_CAPTURE_ENABLE_TIMELIMIT    1122
#define IDC_CAPTURE_TIMELIMIT           1123
#define IDC_CAPTURE_AUDIO_BUFFERSIZE    1124
#define IDC_CAPTURE_FRAMERATE           1125
#define IDC_CAPTURE_ABORT_ESCAPE        1126
#define IDC_CAPTURE_ABORT_SPACE         1127
#define IDC_CAPTURE_ABORT_NONE          1128
#define IDC_VOLUME_LEFT                 1130
#define IDC_VOLUME_RIGHT                1131
#define IDC_ASMBOX                      1133
#define IDC_PROCESSOR                   1134
#define IDC_ENABLE                      1135
#define IDC_DISPLAY_CODE                1136
#define IDC_WIDTH                       1136
#define IDC_FRAMEWIDTH                  1137
#define IDC_WIDTH2                      1137
#define IDC_LINEAR_INTERPOLATION        1138
#define IDC_FRAME_ASPECT1               1138
#define IDC_FRAMERATE_SAMELENGTH        1139
#define IDC_FRAME_ASPECT2               1139
#define IDC_FRAMERATE_SAMELENGTH_VALUE  1140
#define IDC_RELWIDTH                    1140
#define IDC_STATIC_MESSAGE              1143
#define IDC_AVI_REKEY                   1146
#define IDC_AVI_RECOMPUTELENGTH         1147
#define IDC_AVI_COMPATIBILITYMODE       1147
#define IDC_MPEG_I_FRAMES_ONLY          1148
#define IDC_AVI_IGNIDX                  1148
#define IDC_MPEG_IP_FRAMES_ONLY         1149
#define IDC_MPEG_ALL_FRAMES             1150
#define IDC_FINALS_SUCK                 1150
#define IDC_COMPUTER_NAME               1151
#define IDS_VIDEO_FILTERS               1152
#define IDC_EDIT1                       1152
#define IDC_FSNAME                      1152
#define IDC_TIMELIMIT_SETTING           1152
#define IDC_CHUNKS                      1152
#define IDC_DATARATE                    1152
#define IDC_FOURCC                      1152
#define IDC_SAMPLINGRATE_CUSTOM_VAL     1152
#define IDC_DISP                        1152
#define IDC_EDIT                        1152
#define IDC_GAMMA                       1152
#define IDC_INPUTLO                     1152
#define IDC_LIMIT                       1152
#define IDC_EDIT_ADDRESS1               1152
#define IDC_FRAMENUMBER                 1152
#define IDC_LICENSE                     1152
#define IDC_IVTCOFFSET                  1152
#define IDC_WARNING                     1152
#define IDC_STRING                      1152
#define IDC_ALPHAFILE                   1152
#define IDC_CRASH_DETAILS               1152
#define IDC_CUTOFF                      1152
#define IDC_ASPECT_RATIO1               1152
#define IDC_OUTPUTFOLDER                1152
#define IDC_ALIGNMENT                   1152
#define IDC_FILEDESC                    1152
#define IDC_NAME                        1152
#define IDC_CLIP_X0                     1152
#define IDC_COMPRESSION                 1152
#define IDS_VIDEO_FRAMERATE             1153
#define IDC_DEFAULT_DRIVER              1153
#define IDC_FILELIMIT_SETTING           1153
#define IDC_KEYRATE                     1153
#define IDC_AUDIORATE                   1153
#define IDC_EDIT2                       1153
#define IDC_EDIT_FRAMELIMIT             1153
#define IDC_XPOS                        1153
#define IDC_TAPS                        1153
#define IDC_ASPECT_RATIO2               1153
#define IDC_CLIP_X1                     1153
#define IDC_COMPRESSION2                1153
#define IDS_VIDEO_COLORDEPTH            1154
#define IDC_SELECT_CAPTURE_FILE         1154
#define IDC_DISKLIMIT_SETTING           1154
#define IDC_INPUTHI                     1154
#define IDC_FOURCC2                     1154
#define IDC_YPOS                        1154
#define IDC_PADDING_INITIAL             1154
#define IDC_EXPORT                      1154
#define IDC_CLIP_Y0                     1154
#define IDS_VIDEO_COMPRESSION           1155
#define IDC_USE_CURRENT_FILE            1155
#define IDC_DROPLIMIT_SETTING           1155
#define IDC_OUTPUTLO                    1155
#define IDC_CLIP_Y1                     1155
#define IDC_COMPRESSION4                1155
#define IDS_VIDEO_CLIPPING              1156
#define IDC_DEFAULT_CAPFILE             1156
#define IDS_VIDEO_MODE_DIRECT           1157
#define IDC_SAVE_CAPSETTINGS            1157
#define IDC_OUTPUTHI                    1157
#define IDS_VIDEO_MODE_FASTRECOMPRESS   1158
#define IDC_SAVE_AUDIOFORMAT            1158
#define IDS_VIDEO_MODE_NORMALRECOMPRESS 1159
#define IDC_SAVE_VIDEOFORMAT            1159
#define IDS_VIDEO_MODE_FULL             1160
#define IDC_DRIVER_TO_SET               1160
#define IDC_SLOW_PREVIEW                1161
#define IDC_SLOW_OVERLAY                1162
#define IDC_INITIAL_NODISPLAY           1163
#define IDC_INITIAL_PREVIEW             1164
#define IDC_STATIC_FIRSTFRAMENAME       1164
#define IDC_INITIAL_OVERLAY             1165
#define IDC_FILENAME_PREFIX             1166
#define IDC_FILENAME_SUFFIX             1167
#define IDC_FILENAME_DIGITS             1168
#define IDC_DIRECTORY                   1169
#define IDC_SELECT_DIR                  1170
#define IDC_STATIC_LASTFRAMENAME        1171
#define IDC_STATIC_REQCOUNT             1172
#define IDC_STATIC_FRAMECNT             1173
#define IDC_STATIC_FSNAME               1174
#define IDC_STATIC_AUDIOSEGS            1175
#define IDC_VIDEO_BUFFERS               1175
#define IDC_AUDIO_BUFFERS               1176
#define IDC_STATIC_FCINSTALLED          1176
#define IDC_SAVE_COMPRESSION            1177
#define IDC_MPEG_FULLPELPREDICT         1182
#define IDC_MPEG_ACCEPTPARTIAL          1182
#define IDC_CHECK1                      1184
#define IDC_EXTENDED_OPTIONS            1184
#define IDC_AVI_INTERNALMJPEG           1184
#define IDC_DISABLE_THIS_MESSAGE        1184
#define IDC_TIMELIMIT                   1184
#define IDC_DISABLEBUFFERING            1184
#define IDC_USE_DATARATE                1184
#define IDC_LETTERBOX                   1184
#define IDC_NOMORE                      1184
#define IDC_CORRECT                     1184
#define IDC_CUSTOM                      1184
#define IDC_INVTELECINE                 1184
#define IDC_FRAMELIMIT                  1184
#define IDC_TWEAK_TIMER                 1184
#define IDC_SHOWALL                     1184
#define IDC_INVPOLARITY                 1184
#define IDC_LUMA                        1184
#define IDC_LUMANOTCHEVEN               1184
#define IDC_HEX                         1184
#define IDC_ADJUSTVOL                   1184
#define IDC_ALPHABLEND                  1184
#define IDC_AUTOARRANGE                 1184
#define IDC_VERIFY                      1184
#define IDC_AVI_INTERNALDECODER         1184
#define IDC_QUICK                       1184
#define IDC_SHOWIMAGEFORMATS            1184
#define IDC_AUTOSTART                   1184
#define IDC_MATCHCASE                   1184
#define IDC_SINGLE_FB                   1184
#define IDC_CHECKRETCODE                1184
#define IDC_MUXPARTIAL                  1184
#define IDC_BACKGROUND                  1184
#define IDC_USE_ALPHA                   1184
#define IDC_BLEND_CURVE                 1184
#define IDC_ENABLE_AUDIO                1184
#define IDC_AVI_DISABLEOPTIMIZEDIO      1185
#define IDC_DISABLE_ALL_MESSAGES        1185
#define IDC_AUTOLOADSEGMENTS            1185
#define IDC_LUMANOTCHODD                1185
#define IDC_CASELESS                    1185
#define IDC_AUTOCONNECT                 1185
#define IDC_SHOWASPECTRATIOS            1185
#define IDC_MUXPARTIAL2                 1185
#define IDC_USEOUTPUTASTEMP             1185
#define IDC_TARGA_RLE                   1185
#define IDC_CHROMAAGCENEVEN             1186
#define IDC_SHOWFRAMERATES              1186
#define IDC_TIFF_LZW                    1186
#define IDC_CHROMAAGCENODD              1187
#define IDC_TIFF_ZIP                    1187
#define IDC_LUMACOMBEVEN                1188
#define IDC_CURRENT_VALUE               1189
#define IDC_LUMACOMBODD                 1189
#define IDC_FILTER_MODE                 1194
#define IDC_PICK_COLOR                  1195
#define IDC_COLOR                       1196
#define IDC_JOBS                        1198
#define IDC_ADD_AS_JOB                  1200
#define IDC_ERROR                       1201
#define IDC_PERCENT                     1203
#define IDC_AUDIO_FORMAT                1204
#define IDC_VIDEO_AVGBITRATE            1205
#define IDC_VIDEO_IFRAMES               1206
#define IDC_VIDEO_PFRAMES               1207
#define IDC_VIDEO_BFRAMES               1208
#define IDC_VIDEO_FRAMETYPECNT          1209
#define IDC_AUDIO_SIZE                  1210
#define IDC_CURRENTJOB                  1211
#define IDC_VIDEO_FORMAT                1212
#define IDC_TIME_TOTAL                  1213
#define IDC_TIME_LEFT                   1214
#define IDC_DISK_FREE                   1215
#define IDC_VIDEO_SIZE                  1216
#define IDC_VIDEO_RATE                  1217
#define IDC_VIDEO_DATARATE              1218
#define IDC_VIDEO_RATIO                 1219
#define IDC_AUDIO_RATE                  1220
#define IDC_AUDIO_DATARATE              1221
#define IDC_AUDIO_RATIO                 1222
#define IDC_CPU_USAGE                   1223
#define IDC_VMODE_VUMETER               1223
#define IDC_VIDEO_DROPPED               1224
#define IDC_VMODE_OSCILLOSCOPE          1224
#define IDC_VMODE_ANALYZER              1225
#define IDC_VIDEO_AVGFRAMESIZE          1225
#define IDC_VOLUME                      1226
#define IDC_FILE_SIZE                   1226
#define IDC_BALANCE                     1227
#define IDC_AUDIO_CORRECTIONS           1227
#define IDC_STATIC_VOLUME               1228
#define IDC_AUDIO_RESAMPLERATE          1228
#define IDC_STATIC_BALANCE              1229
#define IDC_AUDIO_LATENCY               1229
#define IDC_TABS                        1230
#define IDC_STATIC_PROGRESS             1231
#define IDC_STATIC_PRIORITY             1232
#define IDC_STATIC_LOBOUND              1237
#define IDC_STATIC_HIBOUND              1238
#define IDC_MESSAGE                     1242
#define IDC_FILELIMIT                   1243
#define IDC_DISKLIMIT                   1244
#define IDC_DROPLIMIT                   1245
#define IDC_ROUND_FRAMERATE             1245
#define IDC_CHUNKSIZE                   1246
#define IDC_STATIC_BUFFERSIZE           1248
#define IDC_CHUNKS_UPDOWN               1249
#define IDC_SPILL_DRIVES                1251
#define IDC_EDIT4                       1257
#define IDC_MIN_SIZE                    1257
#define IDC_REPLACESTR                  1257
#define IDC_EDIT5                       1258
#define IDC_MAX_SIZE                    1258
#define IDC_IF_NORMAL                   1260
#define IDC_IF_SPLITNOSWAP              1261
#define IDC_IF_DISCARDFIRST             1262
#define IDC_IF_DISCARDSECOND            1263
#define IDC_IF_SPLITSWAP                1264
#define IDC_STATIC_IFMODE               1265
#define IDC_STATIC_MJPEGOPTS            1266
#define IDC_IF_SWAP                     1267
#define IDC_COMP_LIST                   1267
#define IDC_USE_KEYFRAMES               1268
#define IDC_SIZE_RESTRICTIONS           1270
#define IDC_STATIC_DELTA                1273
#define IDC_STATIC_FOURCC               1274
#define IDC_STATIC_DRIVER               1275
#define IDC_STATIC_DATARATE             1276
#define IDC_STATIC_KEYFRAMES            1277
#define IDC_STATIC_QUALITY              1279
#define IDS_AUDIO_CONVERSION            1280
#define IDC_QUALITY_SLIDER              1280
#define IDS_AUDIO_INTERLEAVE            1281
#define IDC_STATIC_QUALITY_LABEL        1281
#define IDS_AUDIO_SOURCE_NONE           1282
#define IDC_BUTTON1                     1282
#define IDC_PICKCOLOR                   1282
#define IDC_LOGOFILE_BROWSE             1282
#define IDC_BROWSEOUTPUTFOLDER          1282
#define IDC_DUMPSTATUS                  1282
#define IDC_BROWSE                      1282
#define IDC_COMPRESSION_CHANGE          1282
#define IDS_AUDIO_SOURCE_AVI            1283
#define IDC_REGDUMP                     1283
#define IDC_ALPHAFILE_BROWSE            1283
#define IDC_COMPRESSION_CHANGE2         1283
#define IDS_AUDIO_SOURCE_WAV            1284
#define IDC_STATIC_BOMBREASON           1284
#define IDS_AUDIO_COMPRESSION           1285
#define IDC_STATIC_OPTPREVIEW           1285
#define IDC_STATIC_AUDIOBUFFER          1285
#define IDS_AUDIO_MODE_DIRECT           1286
#define IDC_STATIC_READMODE             1286
#define IDC_STATIC_VIDEOBUFFER          1286
#define IDS_AUDIO_MODE_FULL             1287
#define IDC_STATIC_VIDEOSTREAM          1287
#define IDC_STATIC_VIDEOREQUESTS        1287
#define IDC_STATIC_AUDIOSTREAM          1288
#define IDC_STATIC_IOTIME               1288
#define IDC_EDIT_QUALITY                1289
#define IDC_STATIC_PROCTIME             1289
#define IDC_FORCE_FOURCC                1290
#define IDC_MODE_BLEND                  1291
#define IDC_FORCE_HANDLER               1291
#define IDC_MODE_DUP1                   1292
#define IDC_MODE_DUP2                   1293
#define IDC_FORCE_SAMPRATE              1293
#define IDC_MODE_DISCARD1               1294
#define IDC_MODE_DISCARD2               1295
#define IDC_DISP_SPIN                   1296
#define IDC_POINT_LIST                  1297
#define IDC_STATIC1                     1300
#define IDC_STATIC_FILLCOLOR            1303
#define IDC_STATIC_FILTERMODE           1304
#define IDC_SPIN                        1307
#define IDC_SPIN2                       1308
#define IDC_MP3_DECODER                 1308
#define IDC_CALL_STACK                  1310
#define IDC_ACCEPTPARTIAL               1311
#define IDC_OUTPUT_LEVELS               1312
#define IDC_INPUT_LEVELS                1313
#define IDC_INPUTGAMMA                  1314
#define IDC_HISTOGRAM                   1315
#define IDC_ALLFRAMES                   1316
#define IDC_ALLKEYS                     1317
#define IDC_FORMATS                     1317
#define IDC_ONEKEYPERSEC                1318
#define IDC_FRAME_WIDTH                 1318
#define IDC_FRAME_HEIGHT                1319
#define IDC_DELAY                       1319
#define IDC_STATIC_DELAY                1320
#define IDC_GAIN                        1321
#define IDC_STATIC_GAIN                 1322
#define IDC_ADJUSTVIDEOTIMING           1324
#define IDC_THRESHOLD                   1329
#define IDC_TWEAK_TIMER2                1330
#define IDC_EVENTS                      1331
#define IDC_FORMATTAG                   1332
#define IDC_FORMAT                      1333
#define IDC_STATIC_FORMATID             1334
#define IDC_STATIC_BYTESPERBLOCK        1335
#define IDC_STATIC_GRANULARITY          1336
#define IDC_CREDITS                     1337
#define IDC_STATIC_ADDRESS2             1339
#define IDC_STATIC_ADDRESS1             1340
#define IDC_EDIT_ADDRESS2               1341
#define IDC_JUMPTOFRAME                 1342
#define IDC_JUMPTOTIME                  1343
#define IDC_FRAMETIME                   1344
#define IDC_AUTOAPPEND                  1345
#define IDC_IVTC_OFF                    1346
#define IDC_IVTC_RECONFIELDS            1347
#define IDC_IVTC_RECONFIELDSFIXED       1348
#define IDC_IVTC_RECONFRAMESMANUAL      1349
#define IDC_STATIC_IVTCOFFSET           1350
#define IDC_LUMADECIMATEEVEN            1355
#define IDC_LUMADECIMATEODD             1356
#define IDC_CHROMAAGCEVEN               1357
#define IDC_CHROMAKILLEVEN              1358
#define IDC_CHROMAKILLODD               1359
#define IDC_CHROMACOMBEVEN              1360
#define IDC_CHROMACOMBODD               1361
#define IDC_INTERLACEVSEVEN             1362
#define IDC_INTERLACEVSODD              1363
#define IDC_LUMAFULLRANGE               1364
#define IDC_AGCCRUSH                    1365
#define IDC_GAMMACORRECTION             1366
#define IDC_UP                          1367
#define IDC_DOWN                        1368
#define IDC_FIND                        1369
#define IDC_INTERLACED                  1370
#define IDC_SLIDER_VOLUME               1372
#define IDC_SLIDER_CORING               1373
#define IDC_LUMAPEAKEVEN                1374
#define IDC_SLIDER_LUMAPEAKEVEN         1375
#define IDC_TREE                        1375
#define IDC_LUMAPEAKODD                 1376
#define IDC_SLIDER_LUMAPEAKODD          1377
#define IDC_WHITE_POINT                 1378
#define IDC_SLIDER_VDELAY               1379
#define IDC_SLIDER_RIGHT                1380
#define IDC_SECONDARYALPHA              1380
#define IDC_SLIDER_LEFT                 1381
#define IDC_LOGOFILE                    1381
#define IDC_SLIDER_AGCDELAY             1382
#define IDC_FORMAT_TGA                  1382
#define IDC_PREMULTALPHA                1382
#define IDC_SLIDER_BURSTDELAY           1383
#define IDC_FORMAT_BMP                  1383
#define IDC_SLIDER_WHITEDOWN            1384
#define IDC_FORMAT_JPEG                 1384
#define IDC_SLIDER_WHITEUP              1385
#define IDC_FORMAT_PNG                  1385
#define IDC_SPIN_XOFFSET                1389
#define IDC_SPIN_YOFFSET                1390
#define IDC_OPACITY                     1391
#define IDC_STATIC_OPACITY              1392
#define IDC_STATIC_VERSION              1393
#define IDC_CRASH_HELP                  1395
#define IDC_GRAPH                       1396
#define IDC_FREQ                        1397
#define IDC_RATIO                       1398
#define IDC_FACTOR                      1399
#define IDC_PRECISION_NOCHANGE          1400
#define IDC_LOG                         1400
#define IDC_PRECISION_8BIT              1401
#define IDC_PRECISION_16BIT             1402
#define IDC_ERROR_REPORTALL             1402
#define IDC_REASSERT                    1403
#define IDC_ERROR_CONCEAL               1403
#define IDC_PROFILE                     1403
#define IDC_ERROR_DECODE                1404
#define IDC_AUDIO_LENGTH                1404
#define IDC_FILTER                      1407
#define IDS_OPTIONS_PERFORMANCE         1408
#define IDS_OPTIONS_DYNAMICCOMPILATION  1409
#define IDC_QUALITY                     1409
#define IDS_OPTIONS_DISPLAYINPUTVIDEO   1410
#define IDC_TEXT                        1410
#define IDS_OPTIONS_DISPLAYOUTPUTVIDEO  1411
#define IDC_POSITION                    1411
#define IDS_OPTIONS_DISPLAYDECOMPRESSEDOUTPUT 1412
#define IDC_LIST                        1412
#define IDS_OPTIONS_ENABLEMMX           1413
#define IDC_PRECISION                   1413
#define IDS_OPTIONS_SHOWSTATUSWINDOW    1414
#define IDS_OPTIONS_SYNCHRONOUSBLIT     1415
#define IDS_OPTIONS_VERTICALDISPLAY     1416
#define IDS_OPTIONS_DRAWHISTOGRAMS      1417
#define IDS_OPTIONS_SYNCTOAUDIO         1418
#define IDC_AR_NONE                     1418
#define IDS_OPTIONS_PREFERENCES         1419
#define IDC_AR_USE_SOURCE               1419
#define IDC_CHANNELS_NOCHANGE           1420
#define IDS_OPTIONS_DROPFRAMES          1420
#define IDC_AR_USE_RATIO                1420
#define IDC_CHANNELS_MONO               1421
#define IDS_OPTIONS_ENABLEDIRECTDRAW    1421
#define IDC_FRAME_NONE                  1421
#define IDC_CHANNELS_STEREO             1422
#define IDC_FRAME_TO_SIZE               1422
#define IDC_CHANNELS_LEFT               1423
#define IDC_FRAME_AR_CROP               1423
#define IDC_CHANNELS_RIGHT              1424
#define IDC_FRAME_AR_LETTERBOX          1424
#define IDC_SIZE_ABSOLUTE               1425
#define IDC_SIZE_RELATIVE               1426
#define IDC_ALIGNMENT_1                 1427
#define IDC_ALIGNMENT_4                 1428
#define IDC_SLIDER1                     1428
#define IDC_ALIGNMENT_8                 1429
#define IDC_STATIC_LIMIT                1429
#define IDC_ALIGNMENT_16                1430
#define IDC_ALIGNMENT_2                 1431
#define IDC_BITRATE_AUTO                1435
#define IDC_BITRATE_CBR                 1436
#define IDC_BITRATE_VBR                 1437
#define IDC_IMAGE                       1437
#define IDC_RED                         1438
#define IDC_GREEN                       1439
#define IDC_BLUE                        1440
#define IDC_CROP_FAST                   1441
#define IDC_ALPHA                       1441
#define IDC_CROP_PRECISE                1442
#define IDC_STATIC_YCCCROP              1443
#define IDC_RED2                        1446
#define IDC_FIELDORDER_BFF3             1447
#define IDC_GREEN2                      1447
#define IDC_RADIO5                      1448
#define IDC_VORIENT_BOTTOMUP            1448
#define IDC_BLUE2                       1448
#define IDC_DEINTERLACE_NONE            1449
#define IDC_FIELDORDER_BLURRED2         1449
#define IDC_ALPHA2                      1449
#define IDC_DIR_MIDDLERIGHT             1450
#define IDC_DEINTERLACE_NONE2           1450
#define IDC_DIR_TOPRIGHT                1451
#define IDC_DIR_TOPCENTER               1452
#define IDC_SEARCHSTR                   1452
#define IDC_DIR_TOPLEFT                 1453
#define IDC_OUTPUT_RELATIVE             1453
#define IDC_DIR_MIDDLELEFT              1454
#define IDC_OUTPUT_ABSOLUTE             1454
#define IDC_DIR_BOTTOMLEFT              1455
#define IDC_DIR_BOTTOMCENTER            1456
#define IDC_DIR_BOTTOMRIGHT             1457
#define IDC_DIR_MIDDLECENTER            1458
#define IDC_HOTKEY                      1469
#define IDC_BOUNDCOMMANDS               1470
#define IDC_AVAILCOMMANDS               1471
#define IDC_STATIC_BOUNDCOMMANDS        1472
#define IDC_STATIC_AVAILABLECOMMANDS    1473
#define IDC_STATIC_QUICKSEARCH          1474
#define IDC_STATIC_SHORTCUT             1475
#define IDC_SWAP_BUFFERS                1477
#define IDC_SOURCE_HDC                  1478
#define IDC_DEST_HDC                    1479
#define IDC_RADIO2                      1483
#define IDC_VORIENT_TOPDOWN             1483
#define IDC_INPUT_WAV                   1483
#define IDC_OUTPUT_FORMAT               1484
#define IDC_PLANEORDER_CBCR             1486
#define IDC_PLANEORDER_CRCB             1487
#define IDC_PADDING_FRAME               1489
#define IDC_INPUT_FORMAT                1490
#define IDC_CS_NONE                     1492
#define IDC_CS_601                      1493
#define IDC_CS_709                      1494
#define IDC_CR_NONE                     1495
#define IDC_CR_LIMITED                  1496
#define IDC_CR_FULL                     1497
#define IDC_STATIC_COLORSPACE           1498
#define IDC_STATIC_COLORSPACE2          1499
#define IDC_CS2_NONE                    1500
#define IDC_CS2_601                     1501
#define IDC_CS2_709                     1502
#define IDC_CR2_NONE                    1503
#define IDC_INPUT_RAW                   1504
#define IDC_CR2_LIMITED                 1504
#define IDC_LOG_STDOUT                  1505
#define IDC_CR_FULL2                    1505
#define IDC_CR2_FULL                    1505
#define IDC_LOG_STDERR                  1506
#define IDC_TYPE                        1507
#define IDC_CMDLINE                     1508
#define IDC_PROGRAM                     1508
#define IDC_OUTPUTFILENAME              1509
#define IDC_ARGUMENTS                   1510
#define IDC_PREDELETE_OUTPUTFILE        1511
#define IDC_VIDEO_ENCODER               1514
#define IDC_AUDIO_ENCODER               1515
#define IDC_MULTIPLEXER                 1516
#define IDC_FILEEXT                     1517
#define IDC_FORCEPCM                    1520
#define IDC_BYPASSCOMPRESSION           1520
#define IDC_IMPORT                      1521
#define IDC_SHOW_ALL                    1523
#define IDC_COPY                        1524
#define IDC_BUTTON2                     1528
#define IDC_CMDLINE_ARG                 1528
#define IDC_PIXEL_FORMAT                1529
#define IDC_FILTERS_SAVE                1530
#define IDC_STATIC_COLORRANGE           1531
#define IDC_STATIC_COLORRANGE2          1532
#define IDC_PROFILE_LIST                1532
#define IDC_FORMAT_TIFF                 1533
#define IDC_PROFILE_SUMMARY             1533
#define IDC_ACTIVEFORMAT                1534
#define IDC_MATRIX_TITLE                1535
#define IDS_HELP_CONTENTS               1536
#define IDC_CROP_SIZE                   1536
#define IDS_HELP_CHANGELOG              1537
#define IDC_SAVE_AUDIO                  1537
#define IDS_HELP_RELEASENOTES           1538
#define IDC_AUDIO_INFO                  1538
#define IDS_HELP_ABOUT                  1539
#define IDC_SAVE_DONOW                  1539
#define IDC_SAVE_MAKEJOB                1540
#define IDC_CLIP_X0_SPIN                1540
#define IDC_CLIP_X1_SPIN                1541
#define IDC_DRIVER                      1541
#define IDC_CLIP_Y0_SPIN                1542
#define IDC_MASK_ALL                    1542
#define IDC_CLIP_Y1_SPIN                1543
#define IDC_MASK_0                      1543
#define IDC_SHOW_FILTERED               1544
#define IDC_DRIVER_OPTIONS              1544
#define IDC_DRIVER_INFO                 1545
#define IDC_OPEN_SINGLE                 1546
#define IDC_OPEN_SEGMENTS               1547
#define IDC_OPEN_SEQUENCE               1548
#define IDC_INFO_MSG                    1549
#define IDC_MASK_1                      1544
#define IDC_MASK_2                      1545
#define IDC_MASK_3                      1546
#define IDC_MASK_4                      1547
#define IDC_MASK_5                      1548
#define IDC_MASK_6                      1549
#define IDC_MASK_7                      1550
#define IDC_PEAK_0                      1551
#define IDC_PEAK_1                      1552
#define IDC_PEAK_2                      1553
#define IDC_PEAK_3                      1554
#define IDC_PEAK_4                      1555
#define IDC_PEAK_5                      1556
#define IDC_PEAK_6                      1557
#define IDC_PEAK_7                      1558
#define IDC_CH_SPIN0                    1560
#define IDC_CH_0                        1561
#define IDC_CH_1                        1562
#define IDC_CH_SPIN1                    1563
#define IDC_CH_2                        1564
#define IDC_CH_SPIN2                    1565
#define IDC_CH_3                        1570
#define IDC_CH_SPIN3                    1571
#define IDC_CH_4                        1572
#define IDC_CH_SPIN4                    1573
#define IDC_CH_5                        1576
#define IDC_CH_SPIN5                    1577
#define IDC_CH_6                        1578
#define IDC_CH_SPIN6                    1579
#define IDC_CH_7                        1580
#define IDC_CH_SPIN7                    1581
#define IDS_VIDEO_SEEK_START            1664
#define IDS_VIDEO_SEEK_END              1665
#define IDS_VIDEO_SEEK_PREV             1666
#define IDS_VIDEO_SEEK_NEXT             1667
#define IDS_VIDEO_SEEK_KEYPREV          1668
#define IDS_VIDEO_SEEK_KEYNEXT          1669
#define IDS_VIDEO_SEEK_SELSTART         1670
#define IDS_VIDEO_SEEK_SELEND           1671
#define IDS_VIDEO_SEEK_PREVDROP         1672
#define IDS_VIDEO_SEEK_NEXTDROP         1673
#define IDS_EDIT_JUMPTO                 1674
#define IDS_EDIT_DELETE                 1675
#define IDS_EDIT_SETSELSTART            1676
#define IDS_EDIT_SETSELEND              1677
#define IDS_TOOLS_HEXVIEWER             1792
#define IDS_TOOLS_CREATESPARSEAVI       1793
#define IDS_TOOLS_EXPANDSPARSEAVI       1794
#define IDC_CAPTURE_PANEL               1900
#define IDS_CAP_FILE_SETCAPTUREFILE     2048
#define IDS_CAP_FILE_ALLOCATEDISKSPACE  2049
#define IDS_CAP_FILE_EXITCAPTUREMODE    2050
#define IDS_CAP_AUDIO_COMPRESSION       2176
#define IDS_CAP_AUDIO_VOLUMEMETER       2177
#define IDS_CAP_VIDEO_OVERLAY           2304
#define IDS_CAP_VIDEO_PREVIEW           2305
#define IDS_CAP_VIDEO_FORMAT            2306
#define IDS_CAP_VIDEO_SOURCE            2307
#define IDS_CAP_VIDEO_DISPLAY           2308
#define IDS_CAP_VIDEO_COMPRESSION_AVICAP 2309
#define IDS_CAP_VIDEO_COMPRESSION       2309
#define IDS_CAP_VIDEO_COMPRESSION_INTERNAL 2310
#define IDS_CAP_VIDEO_HISTOGRAM         2311
#define IDS_CAP_VIDEO_FILTERS           2312
#define IDS_CAP_VIDEO_ENABLEFILTERING   2313
#define IDS_CAP_VIDEO_PREVIEWHISTOGRAM  2314
#define IDS_CAP_VIDEO_CUSTOMFORMAT      2315
#define IDS_CAP_CAPTURE_SETTINGS        2432
#define IDS_CAP_CAPTURE_PREFERENCES     2433
#define IDS_CAP_CAPTURE_CAPTUREVIDEO    2434
#define IDS_CAP_CAPTURE_CAPTUREVIDEOINTERNAL 2435
#define IDS_CAP_CAPTURE_HIDEONCAPTURE   2436
#define ID_FILE_OPENAVI                 40001
#define ID_FILE_SAVEAVI                 40002
#define ID_AUDIO_CONVERSION             40003
#define ID_VIDEO_FILTERS                40004
#define ID_FILE_SAVEWAV                 40005
#define ID_FILE_QUIT                    40007
#define ID_AUDIO_SOURCE_NONE            40010
#define ID_AUDIO_SOURCE_WAV             40012
#define ID_OPTIONS_DISPLAYINPUTVIDEO    40013
#define ID_OPTIONS_DISPLAYOUTPUTVIDEO   40014
#define ID_VIDEO_FRAMERATE              40015
#define ID_FILE_CLOSEAVI                40016
#define ID_AUDIO_INTERLEAVE             40017
#define ID_VIDEO_OUTPUTDEPTH            40018
#define ID_VIDEO_COLORDEPTH             40018
#define ID_OPTIONS_PERFORMANCE          40019
#define ID_VIDEO_COMPRESSION            40020
#define ID_HELP_ABOUT                   40021
#define ID_FILE_AVIINFO                 40024
#define ID_FILE_PREVIEWAVI              40025
#define ID_HELP_CONTENTS                40026
#define ID_VIDEO_CLIPPING               40027
#define ID_HELP_CHANGELOG               40028
#define ID_OPTIONS_SHOWSTATUSWINDOW     40034
#define ID_DUBINPROGRESS_ABORT          40035
#define ID_VIDEO_FORMAT                 40036
#define ID_VIDEO_SOURCE                 40037
#define ID_VIDEO_DISPLAY                40038
#define ID_FILE_EXITCAPTUREMODE         40040
#define ID_FILE_SETCAPTUREFILE          40041
#define ID_VIDEO_OVERLAY                40042
#define ID_VIDEO_PREVIEW                40043
#define ID_AUDIO_COMPRESSION            40045
#define ID_CAPTURE_SETTINGS             40046
#define ID_CAPTURE_CAPTUREVIDEO         40047
#define ID_FILE_ALLOCATEDISKSPACE       40048
#define ID_FILE_CAPTUREAVI              40049
#define ID_FRAMERATE_CUSTOM             40050
#define ID_OPTIONS_DISPLAYDECOMPRESSEDOUTPUT 40083
#define ID_AUDIO_VOLUMEMETER            40085
#define ID_VIDEO_MODE_DIRECT            40087
#define ID_VIDEO_MODE_FASTRECOMPRESS    40088
#define ID_VIDEO_MODE_NORMALRECOMPRESS  40089
#define ID_VIDEO_MODE_FULL              40090
#define ID_CAPTURE_HIDEONCAPTURE        40091
#define ID_HELP_RELEASENOTES            40092
#define ID_OPTIONS_DYNAMICCOMPILATION   40093
#define ID_OPTIONS_VERTICALDISPLAY      40094
#define ID_AUDIO_MODE_DIRECT            40095
#define ID_AUDIO_MODE_FULL              40096
#define ID_OPTIONS_SYNCTOAUDIO          40099
#define ID_CAPTURE_CAPTUREVIDEOINTERNAL 40100
#define ID_OPTIONS_PREFERENCES          40101
#define ID_HELP_VIEWLOG                 40103
#define ID_OPTIONS_ENABLEDIRECTDRAW     40104
#define ID_FILE_STARTSERVER             40105
#define ID_VIDEO_HISTOGRAM              40106
#define ID_CAPTURE_PREFERENCES          40108
#define ID_FILE_SCRIPTEDITOR            40109
#define ID_FILE_NEWSCRIPT               40110
#define ID_FILE_EXITSCRIPTEDITOR        40111
#define ID_NULL                         40112
#define ID_ADDSETCMD_FRAMERATE          40113
#define ID_ADDSETCMD_FRDECIMATE         40114
#define ID_ADDSETCMD_INPUTDEPTH         40115
#define ID_ADDSETCMD_OUTPUTDEPTH        40116
#define ID_ADDSETCMD_SETSTART           40117
#define ID_ADDSETCMD_ENDPOINT           40118
#define ID_ADDSETCMD_AUDIOMODE          40120
#define ID_ADDSETCMD_VIDEOMODE          40121
#define ID_FILE_SAVEIMAGESEQ            40122
#define ID_FILE_SAVESTRIPEDAVI          40126
#define ID_FILE_SETSTRIPINGSYSTEM       40127
#define ID_FILE_RUNSCRIPT               40128
#define ID_FILE_JOBCONTROL              40129
#define ID_OPTIONS_DROPFRAMES           40130
#define ID_FILE_LOADJOBLIST             40131
#define ID_FILE_SAVEJOBLIST             40132
#define ID_FILE_SETJOBLISTFILENAME      40133
#define ID_EDIT_DELETEDONEJOBS          40134
#define ID_EDIT_FAILEDTOWAITING         40135
#define ID_EDIT_CLEARLIST               40136
#define ID_EDIT_PROCESSDIRECTORY        40137
#define ID_EDIT_WAITINGTOPOSTPONED      40138
#define ID_EDIT_POSTPONEDTOWAITING      40139
#define ID_EDIT_DONETOWAITING           40140
#define ID_VIDEO_COPYSOURCEFRAME        40141
#define ID_VIDEO_SETSTART               40143
#define ID_VIDEO_SETEND                 40144
#define ID_CAPTURE_TEST                 40145
#define ID_FILE_SAVESTRIPEMASTER        40146
#define ID_CAPTURE_DISPLAYLARGETIMER    40147
#define ID_FILE_SAVECOMPATIBLEAVI       40148
#define ID_CAPTURE_STOPCONDITIONS       40149
#define ID_CAPTURE_DISKIO               40156
#define ID_CAPTURE_SPILLSYSTEM          40157
#define ID_CAPTURE_ENABLESPILL          40158
#define ID_FILE_SAVECONFIGURATION       40159
#define ID_FILE_LOADCONFIGURATION       40160
#define ID_DISPLAY_QUARTER              40161
#define ID_DISPLAY_ZOOM_25              40161
#define ID_DISPLAY_HALF                 40162
#define ID_DISPLAY_ZOOM_50              40162
#define ID_DISPLAY_NORMAL               40163
#define ID_DISPLAY_ZOOM_100             40163
#define ID_DISPLAY_DOUBLE               40164
#define ID_DISPLAY_ZOOM_200             40164
#define ID_DISPLAY_QUADRUPLE            40165
#define ID_DISPLAY_ZOOM_400             40165
#define ID_VIDEO_STRETCH                40168
#define ID_VIDEO_COPYOUTPUTFRAME        40169
#define ID_CAPTURE_INFOPANEL            40170
#define ID_VIDEO_PREVIEWHISTOGRAM       40171
#define ID_VIDEO_ENABLEFILTERING        40173
#define ID_VIDEO_CUSTOMFORMAT           40174
#define ID_FILE_APPENDSEGMENT           40176
#define ID_FILE_SAVESEGMENTEDAVI        40177
#define ID_HELP_ONLINE_HOME             40178
#define ID_HELP_ONLINE_FAQ              40179
#define ID_HELP_ONLINE_NEWS             40180
#define ID_HELP_ONLINE_KB               40181
#define ID_CAPTURE_TIMING               40182
#define ID_VIDEO_SWAPFIELDS             40184
#define ID_VIDEO_VRNONE                 40186
#define ID_VIDEO_VR2LINEAR              40187
#define ID_VIDEO_VR2CUBIC               40188
#define ID_VIDEO_NOISEREDUCTION         40189
#define ID_VIDEO_NOISEREDUCTION_THRESHOLD 40190
#define ID_ABORTCAPTURE                 40191
#define ID_CAPTURE_ENABLELOGGING        40192
#define ID_CAPTURE_DISPLAYCAPTURELOG    40193
#define ID_VIDEO_SEEK_SELSTART          40194
#define ID_VIDEO_SEEK_SELEND            40195
#define ID_VIDEO_SEEK_PREVDROP          40196
#define ID_VIDEO_SEEK_NEXTDROP          40197
#define ID_VIDEO_SEEK_PREV              40198
#define ID_VIDEO_SEEK_NEXT              40199
#define ID_VIDEO_SEEK_KEYPREV           40200
#define ID_VIDEO_SEEK_KEYNEXT           40201
#define ID_VIDEO_SEEK_START             40202
#define ID_VIDEO_SEEK_END               40203
#define ID_EDIT_DELETE                  40206
#define ID_VIDEO_CLIPPING_SET           40208
#define ID_VIDEO_CROPPING               40208
#define ID_TOOLS_HEXVIEWER              40209
#define ID_FILE_EXIT                    40210
#define ID_FILE_OPEN                    40211
#define ID_FILE_CLOSE                   40212
#define ID_EDIT_TRUNCATE                40213
#define ID_EDIT_EXTRACT                 40214
#define ID_EDIT_JUMP                    40216
#define ID_EDIT_SETSELSTART             40217
#define ID_EDIT_SETSELEND               40218
#define ID_EDIT_JUMPTO                  40219
#define ID_HELP_WHY                     40220
#define ID_OPTIONS_SWAPPANES            40221
#define ID_HELP_LICENSE                 40222
#define ID_FILE_SAVE                    40223
#define ID_FILE_REVERT                  40224
#define ID_VIDEO_SQUISH_RANGE           40225
#define ID_VIDEO_SQUISH_LOWER           40225
#define ID_VIDEO_BT8X8TWEAKER           40226
#define ID_HELP_KEYS                    40227
#define ID_EDIT_FIND                    40228
#define ID_EDIT_FINDNEXT                40229
#define ID_AUDIO_VOLUME                 40230
#define ID_OPTIONS_PREVIEWPROGRESSIVE   40231
#define ID_OPTIONS_PREVIEWWEAVETFF      40232
#define ID_OPTIONS_PREVIEWWEAVEBFF      40233
#define ID_OPTIONS_PREVIEWBOBTFF        40234
#define ID_OPTIONS_PREVIEWBOBBFF        40235
#define ID_OPTIONS_PREVIEWNONTFF        40236
#define ID_OPTIONS_PREVIEWNONBFF        40237
#define ID_VIDEO_SEEK_PREVONESEC        40238
#define ID_VIDEO_SEEK_NEXTONESEC        40239
#define ID_EDIT_RIFFTREE                40240
#define ID_CAPTURE_ENABLEHWACCEL        40241
#define ID_CAPTURE_HWACCEL_NONE         40242
#define ID_CAPTURE_HWACCEL_TOP          40243
#define ID_CAPTURE_HWACCEL_BOTTOM       40244
#define ID_CAPTURE_HWACCEL_BOTH         40245
#define ID_EDIT_AVIASSIST               40247
#define ID_TOOLS_CREATESPARSEAVI        40248
#define ID_TOOLS_EXPANDSPARSEAVI        40249
#define ID_EDIT_MASK                    40250
#define ID_EDIT_UNMASK                  40251
#define ID_EDIT_RESET                   40252
#define ID_VIDEO_SCANFORERRORS          40253
#define ID_EDIT_PREVRANGE               40256
#define ID_EDIT_NEXTRANGE               40257
#define ID_CAPTURE_STARTONLEFT          40258
#define ID_CAPTURE_AUTOINCREMENT        40259
#define ID_FILE_DECREMENT               40260
#define ID_FILE_INCREMENT               40261
#define ID_OPTIONS_SHUTDOWNWHENFINISHED 40262
#define ID_AUDIO_FILTERS                40263
#define ID_AUDIO_ADVANCEDFILTERING      40264
#define ID_AUDIO_WINMIXER               40265
#define ID_OPTIONS_SHOWLOG              40266
#define ID_VIDEO_ERRORMODE              40267
#define ID_AUDIO_ERRORMODE              40268
#define ID_OPTIONS_SHOWPROFILER         40269
#define ID_FILE_PREVIEWOUTPUT           40271
#define ID_FILE_PREVIEWINPUT            40272
#define ID_DISPLAY_ZOOM                 40274
#define ID_DISPLAY_ASPECTRATIO          40275
#define ID_DISPLAY_AR_PIXEL_1457        40276
#define ID_DISPLAY_AR_FRAME_1333        40277
#define ID_DISPLAY_AR_FRAME_1777        40278
#define ID_DISPLAY_ZOOM_33              40279
#define ID_DISPLAY_ZOOM_66              40280
#define ID_DISPLAY_ZOOM_75              40281
#define ID_DISPLAY_ZOOM_300             40282
#define ID_DISPLAY_ZOOM_150             40283
#define ID_EDIT_COPY                    40284
#define ID_EDIT_CUT                     40285
#define ID_EDIT_PASTE                   40286
#define ID_DISPLAY_AR_FREE              40287
#define ID_DUBINPROGRESS_ABORTFAST      40289
#define ID_EDIT_CLEAR                   40290
#define ID_EDIT_SELECTALL               40291
#define ID_LOG_COPY                     40292
#define ID_LOG_SAVEAS                   40293
#define ID_LOG_CLEAR                    40294
#define ID_DISPLAY_ZOOM_EXACT           40295
#define ID_DISPLAY_FILTER               40296
#define ID_DISPLAY_FILTER_POINT         40297
#define ID_DISPLAY_FILTER_BILINEAR      40298
#define ID_DISPLAY_FILTER_BICUBIC       40299
#define ID_DISPLAY_FILTER_ANY           40300
#define ID_TOOLS_BENCHMARKRESAMPLER     40302
#define ID_DISPLAY_AR_PIXEL_0909        40303
#define ID_DISPLAY_AR_PIXEL_1093        40304
#define ID_DISPLAY_AR_PIXEL_1212        40305
#define ID_DISPLAY_AR_PIXEL_1364        40306
#define ID_DISPLAY_AR_PIXEL_1639        40307
#define ID_DISPLAY_AR_PIXEL_1818        40308
#define ID_DISPLAY_AR_PIXEL_2185        40309
#define ID_DISPLAY_AR_PIXEL_1000        40310
#define ID_DISPLAY_AR_FRAME_1364        40311
#define ID_CAPTURE_STOP                 40312
#define ID_VIDEO_CAPTUREPIN             40313
#define ID_VIDEO_PREVIEWPIN             40314
#define ID_VIDEO_CAPTUREFILTER          40315
#define ID_VIDEO_CROSSBAR               40316
#define ID_VIDEO_CROSSBAR2              40317
#define ID_VIDEO_TUNER                  40318
#define ID_VIDEO_DISCONNECT             40319
#define ID_AUDIO_ENABLE                 40320
#define ID_VIDEO_NODISPLAY              40321
#define ID_CAPTURE_SHOWPROFILER         40322
#define ID_AUDIO_RAWCAPTUREFORMAT       40323
#define ID_AUDIO_PEAKMETER              40324
#define ID_TOOLS_CREATEPALETTIZEDAVI    40325
#define ID_FILE_SETTEXTINFO             40326
#define ID_AUDIO_ENABLEPLAYBACK         40327
#define ID_DEVICE_DEVICESETTINGS        40328
#define ID_VIDEO_VIDEOSOURCE_NOVIDEOSOURCE 40330
#define ID_DEVICE_TUNER_NEXTCHANNEL     40331
#define ID_DEVICE_TUNER_PREVIOUSCHANNEL 40332
#define ID_CAPTURE_ENABLETIMINGLOG      40333
#define ID_CAPTURE_SAVETIMINGLOG        40334
#define ID_VIDEO_SQUISH_UPPER           40335
#define ID_FILE_REOPEN                  40336
#define ID_EDIT_UNDO                    40338
#define ID_EDIT_REDO                    40339
#define ID_FILE_RUNVIDEOANALYSISPASS    40340
#define ID_VIDEO_SEEK_PREVSCENE         40341
#define ID_VIDEO_SEEK_NEXTSCENE         40342
#define ID_CAPTURE_TIMINGGRAPH          40344
#define ID_TOOLS_BACKFACE               40346
#define ID_DEVICE_TUNER_FINEDOWN        40353
#define ID_DEVICE_TUNER_FINEUP          40354
#define ID_FILE_EXPORT                  40355
#define ID_FILE_SAVEFILMSTRIP           40356
#define ID_VIDEO_SMARTRENDERING         40357
#define ID_VIDEO_PRESERVEEMPTYFRAMES    40358
#define ID_VIEW_POSITIONCONTROL         40359
#define ID_VIEW_STATUSBAR               40360
#define ID_VIEW_CURVEEDITOR             40361
#define ID_CAPTURE_SHOWSTATUSBAR        40362
#define ID_CAPTURE_STATUSBAR            40363
#define ID_CAPTURE_FULLSCREEN           40364
#define ID_EXPORT_RAWAUDIO              40367
#define ID_FILE_EXPORT_RAWAUDIO         40368
#define ID_FILE_SAVERAWAUDIO            40369
#define ID_VIEW_AUDIODISPLAY            40370
#define ID_AUDIODISPLAY_WAVEFORM        40371
#define ID_AUDIODISPLAY_SPECTROGRAM     40372
#define ID_AUDIODISPLAY_ZOOMIN          40373
#define ID_AUDIODISPLAY_ZOOMOUT         40374
#define ID_AUDIODISPLAY_SPECTRALBOOST   40375
#define ID_Menu                         40376
#define ID_AUDIODISPLAY_UP_10DB         40384
#define ID_AUDIODISPLAY_UP_6DB          40385
#define ID_AUDIODISPLAY_UP_3DB          40386
#define ID_AUDIODISPLAY_NO_BOOST        40387
#define ID_AUDIODISPLAY_DOWN_3DB        40388
#define ID_AUDIODISPLAY_BOOST_3DB       40389
#define ID_AUDIODISPLAY_BOOST_6DB       40390
#define ID_AUDIODISPLAY_BOOST_10DB      40391
#define ID_AUDIODISPLAY_BOOST_0DB       40392
#define ID_AUDIODISPLAY_BOOST_20DB      40393
#define ID_AUDIODISPLAY_BOOST_12DB      40394
#define ID_DEVICE_TUNERINPUTMODE        40395
#define ID_TUNERINPUTMODE_ANTENNA       40396
#define ID_TUNERINPUTMODE_CABLE         40397
#define ID_DEVICE_ANALOGVIDEOSTANDARD   40398
#define ID_ANALOGVIDEOSTANDARD_NONE     40399
#define ID_ANALOGVIDEOSTANDARD_NTSC     40400
#define ID_ANALOGVIDEOSTANDARD_NTSC40401 40401
#define ID_ANALOGVIDEOSTANDARD_NTSC40402 40402
#define ID_ANALOGVIDEOSTANDARD_PALB     40403
#define ID_ANALOGVIDEOSTANDARD_PALD     40404
#define ID_ANALOGVIDEOSTANDARD_PALH     40405
#define ID_ANALOGVIDEOSTANDARD_PAL      40406
#define ID_ANALOGVIDEOSTANDARD_PAL40407 40407
#define ID_ANALOGVIDEOSTANDARD_PAL40408 40408
#define ID_ANALOGVIDEOSTANDARD_PAL60    40409
#define ID_ANALOGVIDEOSTANDARD_SECAM    40410
#define ID_ANALOGVIDEOSTANDARD_SECAM40411 40411
#define ID_ANALOGVIDEOSTANDARD_SECAM40412 40412
#define ID_ANALOGVIDEOSTANDARD_SECAM40413 40413
#define ID_ANALOGVIDEOSTANDARD_SECAM40414 40414
#define ID_ANALOGVIDEOSTANDARD_SECAM40415 40415
#define ID_ANALOGVIDEOSTANDARD_SECAM40416 40416
#define ID_ANALOGVIDEOSTANDARD_SECAM40417 40417
#define ID_ANALOGVIDEOSTANDARD_PAL40418 40418
#define ID_ANALOGVIDEOSTANDARD_NTSC_M_JAPAN 40419
#define ID_ANALOGVIDEOSTANDARD_NTSC_M   40420
#define ID_ANALOGVIDEOSTANDARD_NTSC_433 40421
#define ID_ANALOGVIDEOSTANDARD_PAL_B    40422
#define ID_ANALOGVIDEOSTANDARD_PAL_D    40423
#define ID_ANALOGVIDEOSTANDARD_PAL_H    40424
#define ID_ANALOGVIDEOSTANDARD_PAL_I    40425
#define ID_ANALOGVIDEOSTANDARD_PAL_M    40426
#define ID_ANALOGVIDEOSTANDARD_PAL_N    40427
#define ID_ANALOGVIDEOSTANDARD_PAL_N_COMBO 40428
#define ID_ANALOGVIDEOSTANDARD_PAL_60   40429
#define ID_ANALOGVIDEOSTANDARD_SECAM_B  40430
#define ID_ANALOGVIDEOSTANDARD_SECAM_D  40431
#define ID_ANALOGVIDEOSTANDARD_SECAM_G  40432
#define ID_ANALOGVIDEOSTANDARD_SECAM_H  40433
#define ID_ANALOGVIDEOSTANDARD_SECAM_K  40434
#define ID_ANALOGVIDEOSTANDARD_SECAM_K1 40435
#define ID_ANALOGVIDEOSTANDARD_SECAM_L  40436
#define ID_ANALOGVIDEOSTANDARD_SECAM_L1 40437
#define ID_CAPTURE_SHOWLOG              40438
#define ID_CAPTURE_HWACCEL_EVENFIRST    40443
#define ID_CAPTURE_HWACCEL_ODDFIRST     40444
#define ID_VIDEO_LEVELS                 40445
#define ID_TOOLS_CREATETESTVIDEO        40446
#define ID_FILE_SAVEANIMATEDGIF         40451
#define ID_FILE_SAVEANIMATEDPNG         40452
#define ID_CAPTURE_HWACCEL_NONINTEVEN   40454
#define ID_CAPTURE_HWACCEL_NONINTODD    40455
#define ID_CAPTURE_HWACCEL_INTERLACED   40457
#define ID_AUDIO_SOURCEAUDIO            40458
#define ID_AUDIO_SOURCE_AVI             40459
#define ID_FILTERCHAIN_SKIP24           40466
#define ID_VIDEO_SKIPFILTERCONVERSION   40467
#define ID_FILE_USELOCALJOBQUEUE        40468
#define ID_FILE_USEREMOTEJOBQUEUE       40469
#define ID_EDIT_CROPTOSELECTION         40482
#define ID_FILE_BATCHWIZARD             40483
#define ID_ADDTOQUEUE_R                 40484
#define ID_ADDTOQUEUE_RESAVEASAVI       40484
#define ID_ADDTOQUEUE_EXTRACTAUDIOTOWAV 40485
#define ID_ADDTOQUEUE_EXTRACTAUDIOASWAV 40485
#define ID_ADDTOQUEUE_EXTRACTRAWAUDIO   40486
#define ID_ADDTOQUEUE_RUNVIDEOANALYSISPASS 40487
#define ID_FILE_QUEUEBATCHOPERATION     40488
#define ID_QUEUEBATCHOPERATION_SAVEASAVI 40489
#define ID_QUEUEBATCHOPERATION_SAVEOLDFORMATAVI 40490
#define ID_QUEUEBATCHOPERATION_SAVECOMPATIBLEAVI 40491
#define ID_QUEUEBATCHOPERATION_SAVESEGMENTEDAVI 40492
#define ID_QUEUEBATCHOPERATION_SAVEIMAGESEQUENCE 40493
#define ID_QUEUEBATCHOPERATION_EXPORTRAWAUDIO 40494
#define ID_QUEUEBATCHOPERATION_SAVEWAV  40495
#define ID_QUEUEBATCHOPERATION_RUNVIDEOANALYSISPASS 40496
#define ID_OPTIONS_WHENFINISHED         40497
#define ID_WHENFINISHED_HIBERNATE       40498
#define ID_WHENFINISHED_DONOTHING       40499
#define ID_WHENFINISHED_SHUTDOWN        40500
#define ID_WHENFINISHED_SLEEP           40501
#define ID_DISPLAY_                     40502
#define ID_DISPLAY_AR_PIXEL_SOURCE      40503
#define ID_DISPLAY_12                   40504
#define ID_DISPLAY_6                    40505
#define ID_DISPLAY_ZOOM_12              40506
#define ID_DISPLAY_ZOOM_6               40507
#define ID_OPTIONS_KEYBOARDSHORTCUTS    40508
#define ID_ALWAYSONTOP                  40509
#define ID_SYSTEM_ALWAYSONTOP           40510
#define ID_VIEW_PANELAYOUT              40511
#define ID_PANELAYOUT_INPUTPANEONLY     40512
#define ID_PANELAYOUT_OUTPUTPANEONLY    40513
#define ID_PANELAYOUT_BOTHPLANES        40514
#define ID_PANELAYOUT_BOTHPANES         40515
#define ID_PANELAYOUT_AUTO              40516
#define ID_PANELAYOUT_AUTOSIZE          40517
#define ID_EXPORT_RAWVIDEO              40518
#define ID_QUEUEBATCHOPERATION_EXPORTRAWVIDEO 40519
#define ID_FILE_SAVERAWVIDEO            40520
#define ID_EXPORT_USINGEXTERNALENCODER  40521
#define ID_FILE_EXPORTEXTERNALENCODER   40522
#define ID_OPTIONS_EXTERNALENCODERS     40523
#define ID_QUEUEBATCHOPERATION_EXPORTUSINGEXTERNALENCODER 40524
#define ID_VIDEO_COPYSOURCEFRAMENUMBERTOCLIPBOARD 40525
#define ID_VIDEO_COPYOUTPUTFRAMENUMBERTOCLIPBOARD 40526
#define ID_VIDEO_COPYSOURCEFRAMENUMBER  40527
#define ID_VIDEO_COPYOUTPUTFRAMENUMBER  40528
#define ID_FILE_MORE                    40529
#define ID_FILE_MODE                    40530
#define ID_TOOLS_OPENNEWPROGRAMINSTANCE 40531
#define ID_TOOLS_FILEMANAGEMENT         40532
#define ID_FILEMANAGEMENT_DELETEANDCLOSE 40533
#define ID_FILEMANAGEMENT_OPENPREVIOUSFILE 40534
#define ID_FILEMANAGEMENT_OPENNEXTFILE  40535
#define ID_TRIAGE_DELETEANDCLOSE        40536
#define ID_TRIAGE_OPENPREVIOUSFILE      40537
#define ID_TRIAGE_OPENNEXTFILE          40538
#define ID_FILE_DELETEANDCLOSE          40539
#define ID_FILE_OPENPREVIOUSFILE        40540
#define ID_FILE_OPENNEXTFILE            40541
#define ID_FILE_CLOSEANDDELETE          40542
#define ID_FILE_NEWINSTANCE             40543
#define ID_FILE_OPENPREVIOUS            40544
#define ID_FILE_OPENNEXT                40545
#define ID_CONTEXTMENUS_LIST            40546
#define ID_LIST_NAMEOUTPUT              40547
#define ID_LIST_ADDINPUT                40548
#define ID_FILTERLIST_NAMEOUTPUT        40549
#define ID_FILTERLIST_ADDINPUT          40550
#define ID_OPTIONS_PLUG                 40551
#define ID_OPTIONS_PLUGINS              40552
#define ID_FILE_LOADPROJECT             40555
#define ID_FILE_SAVEPROJECT             40556
#define ID_FILE_SAVEPROJECTAS           40557
#define ID_FILE_SAVEIMAGE               40559
#define ID_VIDEO_FILTERS_HIDE           40560
#define ID_FILTERLIST_EXTRAVIEW         40561
#define ID_FILTERLIST_ADDFILTERBEFORE   40562
#define ID_FILTERLIST_ADDFILTERAFTER    40563
#define ID_FILTERLIST_DELETE            40564
#define ID_EXPORT_DRIVERTOOL0           40565
#define ID_EXPORT_DRIVERTOOL1           40566
#define ID_EXPORT_DRIVERTOOL2           40567
#define ID_EXPORT_DRIVERTOOL3           40568
#define ID_VIDEO_SEEK_STOP              40569
#define ID_EDIT_SETMARKER               40570
#define ID_EDIT_CLEARMARKERS            40571
#define ID_TOOLS_PLUGIN                 40573
#define ID_TOOLS                        40574
#define ID_DISPLAY_MODE                 40575
#define ID_DISPLAY_DEFAULT              40576
#define ID_DISPLAY_COLOR                40582
#define ID_DISPLAY_ALPHA                40583
#define ID_DISPLAY_BLENDCHECKER         40584
#define ID_DISPLAY_BLEND0               40585
#define ID_DISPLAY_BLEND1               40586
#define ID_EDIT_MARKERSFROMKEYS         40587
#define ID_EXPORT_STREAM_COPY           40588
#define ID_TOOLS_BENCHMARKANALYZEPASS   40589
#define ID_VIEW_MAXIMIZE                40590
#define ID_AUDIO_CAPTUREFILTER          40591
#define ID_OPTIONS_DROPSEEKING          40592
#define ID_AUDIO_CHANNELS               40593
#define ID_AUDIOMODE_11KHZ_8MONO        41000
#define ID_AUDIOMODE_11KHZ_8STEREO      41001
#define ID_AUDIOMODE_11KHZ_16MONO       41002
#define ID_AUDIOMODE_11KHZ_16STEREO     41003
#define ID_AUDIOMODE_22KHZ_8MONO        41004
#define ID_AUDIOMODE_22KHZ_8STEREO      41005
#define ID_AUDIOMODE_22KHZ_16MONO       41006
#define ID_AUDIOMODE_22KHZ_16STEREO     41007
#define ID_AUDIOMODE_32KHZ_8MONO        41008
#define ID_AUDIOMODE_32KHZ_8STEREO      41009
#define ID_AUDIOMODE_32KHZ_16MONO       41010
#define ID_AUDIOMODE_32KHZ_16STEREO     41011
#define ID_AUDIOMODE_44KHZ_8MONO        41012
#define ID_AUDIOMODE_44KHZ_8STEREO      41013
#define ID_AUDIOMODE_44KHZ_16MONO       41014
#define ID_AUDIOMODE_44KHZ_16STEREO     41015
#define ID_AUDIOMODE_48KHZ_8MONO        41016
#define ID_AUDIOMODE_48KHZ_8STEREO      41017
#define ID_AUDIOMODE_48KHZ_16MONO       41018
#define ID_AUDIOMODE_48KHZ_16STEREO     41019
#define ID_FRAMERATE_6000FPS            41050
#define ID_FRAMERATE_3000FPS            41051
#define ID_FRAMERATE_2500FPS            41052
#define ID_FRAMERATE_2000FPS            41053
#define ID_FRAMERATE_1500FPS            41054
#define ID_FRAMERATE_1200FPS            41055
#define ID_FRAMERATE_1000FPS            41056
#define ID_FRAMERATE_500FPS             41057
#define ID_FRAMERATE_5994FPS            41058
#define ID_FRAMERATE_2997FPS            41059
#define ID_FRAMERATE_1998FPS            41060
#define ID_FRAMERATE_1499FPS            41061
#define ID_FRAMERATE_1199FPS            41062
#define ID_FRAMERATE_999FPS             41063
#define ID_FRAMERATE_3030FPS            41064
#define ID_FRAMERATE_2941FPS            41065
#define ID_FRAMERATE_1515FPS            41066
#define ID_FRAMERATE_1493FPS            41067
#define ID_VIDEO_CAPTURE_DRIVER         41100
#define ID_AUDIO_CAPTURE_DRIVER         41150
#define ID_AUDIO_CAPTURE_INPUT          41200
#define ID_AUDIO_CAPTURE_SOURCE         41250
#define ID_VIDEO_CAPTURE_SOURCE         41300
#define ID_MRU_FILE0                    50000
#define ID_MRU_FILE1                    50001
#define ID_MRU_FILE2                    50002
#define ID_MRU_FILE3                    50003
#define ID_AUDIO_SOURCE_AVI_0           50100
#define ID_PLUGIN_TOOL                  50200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         40594
#define _APS_NEXT_CONTROL_VALUE         1562
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
